# SPDX-FileCopyrightText: 2025 Mikael Nordin <kano@sunet.se>
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Lint PHP

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lint-php-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Check coding style
        run: composer cs:check
